### ISSUE TITLE
Arguments of tool is always empty

### ISSUE THREAD

**Issue by dacom-dark-sun** [dexaai/dexter#20]
I am using an [openopenAI](https://github.com/transitive-bullshit/OpenOpenAI) project in which I apply a tool call in two variations:

- retrieval for extracting data from a file
- function_call for invoking image generation

In both cases, the same problem arises: the toolCall object does not contain arguments in the function. Consequently, when calling file access, an error occurs when attempting to parse json. And when calling image generation, the arguments should include a prompt, which is also not delivered.

Reproduction steps:

Create a function to retrieve information from a file and access it. As a result, an error occurs:
```
JSONError: Unexpected end of JSON input while parsing empty string
```

This is related to the fact that the function.arguments object is empty.

```
toolCall: {
index: 0,
id: 'call_UEn7arSct776zKLJVyMY4o7Q',
type: 'function',
function: { name: 'retrieval', arguments: '' }
}
```

Create a function for image generation and access it. As a result, an error occurs: 
```JSONError: Unexpected end of JSON input while parsing empty string```

Because the same object with arguments will be empty.

After conducting an investigation, I discovered that dexter is not returning the arguments for function calls. It's possible that something has changed on openAI's end in recent weeks, making this functionality unavailable now?

What should I do? Where should I look?

**Comment by rileytomasek** [comment]
Thanks for the report, @dacom-dark-sun. Are you sure this is a Dexter issue and not an [openopenAI](https://github.com/transitive-bullshit/OpenOpenAI) issue? If yes, can you share a minimal repro example using just Dexter so I can look into it.
