### ISSUE TITLE
Support for other stores

### ISSUE THREAD

**Issue by umaar** [dexaai/dexter#24]
Hey do you plan to provide support for other data stores? A free one that could be self hosted would be nice.

**Comment by rileytomasek** [comment]
The [Pinecone implementation](https://github.com/dexaai/dexter/tree/master/src/datastore/pinecone) extends `AbstractDatastore`. We're open to PRs that follow the same pattern for different providers.

**Comment by rileytomasek** [comment]
Closing this as a duplicate of #12
