### ISSUE TITLE
Upgrade pinecone-client to v2?

### ISSUE THREAD

**Issue by transitive-bullshit** [dexaai/dexter#8]
@rileytomasek is there a reason it's still on v1? Happy to create a PR.

**Comment by rileytomasek** [comment]
@transitive-bullshit nope, it should be on v2. The v2 release was mostly just upgrading min Node version and dropping CJS support so it should be straightforward.

**Comment by transitive-bullshit** [comment]
Fixed in https://github.com/dexaai/dexter/pull/7
